### ISSUE TITLE
Red Java Exception error when attempting to save

### ISSUE THREAD

**Issue by talllguy** [statusbits/smartthings-vlc#4]
Got this error when copying the ab29b247810925dee27f345bc5e3f0b277768277 code into ST IDE.

![2015-02-09 14_36_39-123](https://cloud.githubusercontent.com/assets/1827881/6114020/3d7ea332-b069-11e4-8044-f0cac63681b1.png)

**Comment by statusbits** [comment]
Looks like you're trying to create a Smart App. This is a "Device Type".

**Comment by talllguy** [comment]
Ah, my mistake. I'll try again.
